# Generated by Django 5.0.1 on 2024-02-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'managed': False},
        ),
    ]
