# Generated by Django 5.0.1 on 2024-02-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_userdetails_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
